name: Deploy to Booklyst UAT
on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ deploy-uat ]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to UAT
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USER }}
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/laravel
          echo "Deploying application ..."
          (php artisan down --message 'The app is being (quickly!) updated. Please try again in a minute.') || true
          git fetch origin master
          git reset --hard origin/master
          composer install --no-interaction --prefer-dist --optimize-autoloader
          npm install
          npm run production
          php artisan migrate --force
          php artisan config:cache
          php artisan optimize
          php artisan up
          echo "Application deployed!"
